import fs from "fs/promises";
import path from "path";
import { ensureDirectory } from "../utils/files.js";

const ORQ_FOLDER = "__orq__";

/**
 * StringReplacer.ts 템플릿
 */
export function getStringReplacerTemplate(): string {
  return `/**
 * URL 경로 파라미터 치환 유틸리티
 * Generated by openapi-rq
 */
export class StringReplacer {
  private text: string;

  constructor(text: string) {
    this.text = text;
  }

  /**
   * URL에서 스펙 이름 접두사 제거 및 경로 파라미터 치환
   * @example "PETSTORE:/pet/{petId}" + { petId: 1 } => "/pet/1"
   */
  replaceText(params: Record<string, string | number>): string {
    // 스펙 이름 접두사 제거 (예: "PETSTORE:/pet/{petId}" => "/pet/{petId}")
    let result = this.text.replace(/^[A-Z][A-Z0-9_]*:/, "");

    // 경로 파라미터 치환
    result = result.replace(/\\{(\\w+)\\}/g, (match, key) => {
      const value = params[key];
      return value !== undefined ? String(value) : match;
    });

    return result;
  }

  /**
   * URL에서 경로 파라미터 목록 추출
   */
  getPlaceholders(): string[] {
    const matches = this.text.match(/\\{(\\w+)\\}/g);
    return matches ? matches.map((m) => m.slice(1, -1)) : [];
  }
}
`;
}

/**
 * httpClient.ts 템플릿
 */
export function getHttpClientTemplate(): string {
  return `/**
 * HTTP Client Bootstrap (axios only)
 * Generated by openapi-rq
 *
 * Usage:
 * import axios from "axios";
 * import { setHttpClient } from "./__orq__";
 *
 * const instance = axios.create({ baseURL: "/api" });
 * setHttpClient(instance);
 */
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from "axios";

let httpClient: AxiosInstance | null = null;

/**
 * HTTP 클라이언트 설정
 */
export function setHttpClient(client: AxiosInstance): void {
  httpClient = client;
}

/**
 * HTTP 클라이언트 반환
 */
export function getHttpClient(): AxiosInstance {
  if (!httpClient) {
    throw new Error(
      "HTTP client not initialized. Call setHttpClient(axiosInstance) in your app bootstrap."
    );
  }
  return httpClient;
}

/**
 * axios 응답에서 data 추출 헬퍼
 */
export function extractData<T>(response: AxiosResponse<T>): T {
  return response.data;
}

/**
 * 요청 설정 타입
 * 파일 업로드/다운로드, 커스텀 헤더 등에 사용
 */
export interface RequestConfig {
  headers?: Record<string, string>;
  responseType?: AxiosRequestConfig["responseType"];
  onUploadProgress?: AxiosRequestConfig["onUploadProgress"];
  onDownloadProgress?: AxiosRequestConfig["onDownloadProgress"];
  timeout?: number;
  signal?: AbortSignal;
}
`;
}

/**
 * index.ts 템플릿
 */
export function getIndexTemplate(): string {
  return `export { StringReplacer } from "./StringReplacer.js";
export { setHttpClient, getHttpClient, extractData, type RequestConfig } from "./httpClient.js";
`;
}

/**
 * __orq__ 폴더 및 유틸리티 파일 생성
 */
export async function ensureOrqFolder(outputPath: string): Promise<string> {
  const orqPath = path.join(outputPath, ORQ_FOLDER);
  await ensureDirectory(orqPath);
  return orqPath;
}

/**
 * 모든 유틸리티 파일 생성
 */
export async function generateUtilityFiles(outputPath: string): Promise<void> {
  const orqPath = await ensureOrqFolder(outputPath);

  await Promise.all([
    fs.writeFile(path.join(orqPath, "StringReplacer.ts"), getStringReplacerTemplate()),
    fs.writeFile(path.join(orqPath, "httpClient.ts"), getHttpClientTemplate()),
    fs.writeFile(path.join(orqPath, "index.ts"), getIndexTemplate()),
  ]);
}

/**
 * 유틸리티 파일 존재 여부 확인
 */
export async function orqFolderExists(outputPath: string): Promise<boolean> {
  const orqPath = path.join(outputPath, ORQ_FOLDER);
  try {
    await fs.access(orqPath);
    return true;
  } catch {
    return false;
  }
}
