import fs from "fs/promises";
import path from "path";
import { ensureDirectory } from "../utils/files.js";

const ORQ_FOLDER = "__orq__";

/**
 * StringReplacer.ts 템플릿
 */
export function getStringReplacerTemplate(): string {
  return `/**
 * URL 경로 파라미터 치환 유틸리티
 * Generated by openapi-rq
 */
export class StringReplacer {
  private template: string;

  constructor(template: string) {
    this.template = template;
  }

  /**
   * URL에서 스펙 이름 접두사 제거 및 경로 파라미터 치환
   * @example "PETSTORE:/pet/{petId}" + { petId: 1 } => "/pet/1"
   */
  replaceText(params: Record<string, string | number | undefined>): string {
    // 스펙 이름 접두사 제거 (예: "PETSTORE:/pet/{petId}" => "/pet/{petId}")
    let result = this.template.replace(/^[A-Z][A-Z0-9_]*:/, "");

    // 경로 파라미터 치환
    result = result.replace(/\\{(\\w+)\\}/g, (match, key) => {
      const value = params[key];
      if (value === undefined || value === null) {
        console.warn(\`StringReplacer: Missing value for placeholder "\${key}"\`);
        return match;
      }
      return String(value);
    });

    return result;
  }

  /**
   * Get original template
   */
  getTemplate(): string {
    return this.template;
  }

  /**
   * URL에서 경로 파라미터 목록 추출
   */
  getPlaceholders(): string[] {
    const matches = this.template.match(/\\{(\\w+)\\}/g);
    return matches ? matches.map((m) => m.slice(1, -1)) : [];
  }
}
`;
}

/**
 * httpClient.ts 템플릿
 */
export function getHttpClientTemplate(): string {
  return `/**
 * HTTP Client Bootstrap (axios only)
 * Generated by openapi-rq
 *
 * @example
 * // Set up once at app bootstrap
 * import axios from "axios";
 * import { setHttpClient } from "@/api/__orq__/httpClient";
 *
 * const instance = axios.create({ baseURL: "/api" });
 * setHttpClient(instance);
 */
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from "axios";

/**
 * Axios config type excluding params and data (managed by generated code).
 * Use this to inject custom headers, responseType, onUploadProgress, etc.
 *
 * @example
 * // File upload with progress
 * uploadFile({
 *   body: formData,
 *   config: {
 *     headers: { 'Content-Type': 'multipart/form-data' },
 *     onUploadProgress: (e) => console.log(e.loaded / e.total)
 *   }
 * });
 *
 * // File download as blob
 * downloadFile({
 *   pathParams: { fileId },
 *   config: { responseType: 'blob' }
 * });
 */
export type RequestConfig = Omit<AxiosRequestConfig, 'params' | 'data'>;

let httpClient: AxiosInstance | null = null;

export function setHttpClient(client: AxiosInstance): void {
  httpClient = client;
}

export function getHttpClient(): AxiosInstance {
  if (!httpClient) {
    throw new Error(
      "HTTP client not initialized. Call setHttpClient(axiosInstance) in your app bootstrap."
    );
  }
  return httpClient;
}

/**
 * Helper to extract data from axios response
 */
export async function unwrap<T>(promise: Promise<AxiosResponse<T>>): Promise<T> {
  const response = await promise;
  return response.data;
}
`;
}

/**
 * index.ts 템플릿
 */
export function getIndexTemplate(): string {
  return `/**
 * API Utilities
 * Generated by openapi-rq
 */
export { StringReplacer } from "./StringReplacer";
export { setHttpClient, getHttpClient, unwrap, type RequestConfig } from "./httpClient";
`;
}

/**
 * __orq__ 폴더 및 유틸리티 파일 생성
 */
export async function ensureOrqFolder(outputPath: string): Promise<string> {
  const orqPath = path.join(outputPath, ORQ_FOLDER);
  await ensureDirectory(orqPath);
  return orqPath;
}

/**
 * 모든 유틸리티 파일 생성
 */
export async function generateUtilityFiles(outputPath: string): Promise<void> {
  const orqPath = await ensureOrqFolder(outputPath);

  await Promise.all([
    fs.writeFile(path.join(orqPath, "StringReplacer.ts"), getStringReplacerTemplate()),
    fs.writeFile(path.join(orqPath, "httpClient.ts"), getHttpClientTemplate()),
    fs.writeFile(path.join(orqPath, "index.ts"), getIndexTemplate()),
  ]);
}

/**
 * 유틸리티 파일 존재 여부 확인
 */
export async function orqFolderExists(outputPath: string): Promise<boolean> {
  const orqPath = path.join(outputPath, ORQ_FOLDER);
  try {
    await fs.access(orqPath);
    return true;
  } catch {
    return false;
  }
}
